#!/bin/bash
# Default values
FORCE_MODE=false
GIT=false
VERSION="1.0.0"
# Version checking 
if [ "$1" = "--version" ]; then
    echo "mkproj version $VERSION"
    exit 0
fi
# Look for -p -g -v flag 
while getopts "fgv" opt; do
  case $opt in
    f) FORCE_MODE=true ;;
    g) GIT=true;;
    v) echo "mkproj version $VERSION" 
       exit 0 ;; 
    h)
      echo "Usage: mkproj [options] <project_name>"
      echo
      echo "Options:"
      echo "  -f    Force overwrite existing directory"
      echo "  -g    Initialize git repository"
      echo "  -v    Show version"
      exit 0
      ;;
    *) echo "Invalid option"; exit 1 ;;
  esac
done

shift $((OPTIND-1))

name="$1" 
if [ -z "$name" ]; then
	echo "Usage: mkproj <project_name>"
	exit 1 
fi 
 

if [ -d "$name" ]; then
	if "$FORCE_MODE"; then
		echo "Are you sure you want to rewrite existing directory? (Y/N)"
                read -r OPT 
                case "$OPT" in
                        y|Y) echo "Rewriting Directory..." 
			     rm -rf -- "$name" ;;
                        n|N) echo "Abandoning progress. Choose a different name you wittle dumb dumb (,,,'-',,,)."
                           exit 1 ;;
                        *) echo "Unknown command. Abandoning progress."
                           exit 1 ;;
                esac
	else 
		echo "Unable to create Directory $name. Directory already exists." 
		exit 1 
	fi
fi

mkdir -p "$name"
cd "$name" || exit 1 
if $GIT; then 
cat <<EOF > .gitignore
venv/
__pycache__/
*.pyc
EOF
git init
fi 
python3 -m venv venv
touch main.py
touch requirements.txt
echo "# $name" > README.md
echo "Directory $name successfully created."
echo "Run: cd $name && source venv/bin/activate"


